title: CodeNexus 
description: Connecting ideas to solutions, one problem at a time!
theme: minimal-mistakes

author:
  name: "Aditya N. Khatawkar"
  email: "adityakhatawkar2@gmail.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
